# fly.toml app configuration file generated for datingapp-weathered-rain-3828 on 2025-03-07T00:40:14+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingapp-weathered-rain-3828'
primary_region = 'bom'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dmabbcbbe"
  CloudinarySettings__ApiKey="295455932442858"

[build]
  image = 'jefferywhite/datingapp:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
